### PR TITLE
Prevent a too big file dialog

### PR DESCRIPTION
**Pull request by tsujan**
Fixes https://github.com/lxqt/libfm-qt/issues/244

### CODE REVIEW

**Comment by PCMan** [comment]
@tsujan maybe we can use the facilities provided by Qt?
http://doc.qt.io/qt-5/restoring-geometry.html

**Comment by tsujan** [comment]
@PCMan Yes but, here, the whole point is subtracting `QSize(2, 2)` because, apparently, some WMs make the window full-screen if its size is that of the desktop.

**Comment by PCMan** [comment]
@tsujan I thought Qt already handled that. So it seems that we need to handle this ourselves?
Apart from size, we might also need to keep window state like "fullscreen" or "maxmized".
They are defined in NETWM protocols and I guess Qt more or less support them?
Standard conforming WMs should handle the hints properly.

**Comment by PCMan** [comment]
@tsujan The PR looks good to me. Just curious if Qt handles the window size issue better so we can let Qt do the heavy lifting instead. If it doesn't, then please merge this.

**Comment by tsujan** [comment]
@PCMan Qt handles the win size/state well; the problem is the WM, which may enforce a state.

On second thought, it's good to add the standard shortcut `F11` for (un-)full-screening and do as you suggested. Do you agree? Can I close this and make another PR later?

**Comment by agaida** [comment]
F11 sounds like a good idea for this special case

**Comment by tsujan** [comment]
OK. I think @PCMan agrees too. Closing this.

**Pull request closed without merging**
