### PR TITLE
updated *.ts files

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
Looks like also Turkish has similar issues as Hebrew:

```
Updating 'src/translations/libfm-qt_tr.ts'...
    Found 312 source text(s) (5 new and 307 already existing)
    Removed 1 obsolete entries
    Same-text heuristic provided 1 translation(s)
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.

```

**Comment by tsujan** [comment]
> Looks like also Turkish has similar issues as Hebrew

Trust Qt. It has always been reliable in this regard.

**Comment by tsujan** [comment]
BTW, a new translatable string is added by a recent merge (https://github.com/lxqt/libfm-qt/pull/706). So, another update is needed.

**Comment by stefonarch** [comment]
> BTW, a new translatable string is added by a recent merge (#706). So, another update is needed.

Done, can you have a look?

**Comment by tsujan** [comment]
It's good to merge.

**Review by tsujan — APPROVED** [review]

**Pull request merged**
