### PR TITLE
Workaround for GLib's recursive moving error, e.g. with bound mounts

### PR DESCRIPTION
**Pull request by tsujan**
`g_file_move()` may not work recursively on the same filesystem, especially with bound mounts (to `/mnt`, for example) and give the `G_IO_ERROR_WOULD_RECURSE` error. This patch ignores the error and tries our `FileTransferJob::copyFile()`.

Closes https://github.com/lxqt/pcmanfm-qt/issues/943

### CODE REVIEW

**Comment by agaida** [comment]
You are a genius - will test it with some more cases before merge - anyways GTM

**Comment by tsujan** [comment]
I'm not. PCMan's code is neatly organized.

**Comment by agaida** [comment]
only nitpicking - it isn't limited to /mnt

just try 
```
cd ~
mkdir -p foo/bar foo/baz
mount -B ~/Downloads foo/bar
mount -B ~/Documents foo/baz
```
and have a bit fun.

**Comment by tsujan** [comment]
> only nitpicking - it isn't limited to /mnt

I'd suspected that but the code is independent from /mnt.

**Comment by agaida** [comment]
https://i.imgur.com/R5SzECR.png ;)

**Comment by tsujan** [comment]
>  would you be so kind and change the comments and PR description that way?

Inside the code, I've said,  "Specially with mounts bound to /mnt....", which means it isn't limited to /mnt.

As for the PR comment, OK, I'll add "for example".

Is everything else OK? I mean, could I merge it after changing the PR comment?

**Comment by tsujan** [comment]
Please also note that this isn't even limited to bound mounts; it's for any occurrence of G_IO_ERROR_WOULD_RECURSE, with or without bound mounts.

**Comment by agaida** [comment]
i think so

**Comment by tsujan** [comment]
> i think so

I'm sure ;)

Will do it tonight, after finishing a job about lximage-qt.

**Comment by tsujan** [comment]
Changed the commit explanation as well as the title and explanation of this page (PR).

**Comment by tsujan** [comment]
BTW, gnome users don't encounter this issue with Nautilus because Nautilus doesn't use `g_file_move()` but something like our `FileTransferJob::copyFile()` *everywhere*. Maybe, the code was written before `g_file_move()` was introduced; I don't know.

Anyhow, our code shouldn't fail anymore because `FileTransferJob::copyFile()` is the fallback now.

**Comment by agaida** [comment]
unblocked for debian buster

**Comment by tsujan** [comment]
> unblocked for debian buster

Any plan for a point release? I don't think it'll be needed if the next LXQt version is going to be released 4-5 months later.

**Pull request merged**
