### PR TITLE
s/sub directories/subdirectories/ simple typo fix

### PR DESCRIPTION
**Pull request by ianorlin**
This fixes an issue I reported mistakenly in pcmanfm-qt https://github.com/lxqt/pcmanfm-qt/issues/883 that can be closed after this is merged.

### CODE REVIEW

**Comment by agaida** [comment]
merge after release - it will wreck translations. (This will cause the few next bug reports)

**Comment by tsujan** [comment]
@agaida You may have forgotten to merge this one.

**Comment by agaida** [comment]
no - if we merge it now all translations will be lost for this item - so i would prefer to merge it later

**Comment by tsujan** [comment]
Oh, I understand. In my projects, I manually edit all translation files in such cases and that's very boring.

**Comment by agaida** [comment]
@ianorlin - sorry it took so long

**Pull request merged**
