### PR TITLE
Handle renaming of files, whose names have invalid encodings

### PR DESCRIPTION
**Pull request by tsujan**
The original fix was made by @damianatorrpm (see https://github.com/lxqt/libfm-qt/pull/507).

Closes https://github.com/lxqt/libfm-qt/issues/138

### CODE REVIEW

**Comment by damianatorrpm** [comment]
It does not close https://github.com/lxqt/libfm-qt/issues/138 just yet it shows the correct edit name to edit. The second part will be in a different PR implementing similar for Fm::FileOperation

**Comment by tsujan** [comment]
> The second part will be in a different PR implementing similar for Fm::FileOperation

I'll wait for you to tell me why `g_file_move` doesn't work and what does -- as I said elsewhere, all file names have correct encodings here. In the meanwhile, I might consult Nautilus' code if I find the time.

Please also note that we don't want a too complex workaround.

**Comment by damianatorrpm** [comment]
I already have an idea about that the most complex solution I can imagine would be 
an if (uriScheme=='google-drive') but I will look into this after setting up an issuer report and the gym.

**Comment by tsujan** [comment]
As you might have guessed my reply, we shouldn't make an exception for google-drive.

We rename files by using `g_file_move`, which probably doesn't work with google-drive. Other ways of renaming are `g_file_set_display_name`  and `g_file_set_display_name_async`. To use them instead of `g_file_move`, we'll need a lot of code change and, more importantly, a lot of tests because we don't want to damage what works just for a special case.

I'm really not sure that it's worth the effort but I agree that it's worth considering.

I close this because it doesn't add anything to the current functionality. A clean solution will need a code restructuring by using `g_file_set_display_name(_async)`.

**Comment by tsujan** [comment]
Update:

I took a very simple approach, replaced `g_file_move` with `g_file_set_display_name` and, contrary to what the functions name said, the *real* file name was changed, not its display name.

That's a little confusing but if `g_file_set_display_name` changes the real file name, it might be good for us. However, your test is needed to see if it solves https://github.com/lxqt/libfm-qt/issues/138.

To test, use this patch but change `changeFileName` as follows:

```c++
bool changeFileName(const Fm::FilePath& filePath, const QString& newName, QWidget* parent, bool showMessage) {
    Fm::GErrorPtr err;
    if(!g_file_set_display_name(filePath.gfile().get(),
                                newName.toLocal8Bit().constData(),
                                nullptr, /* make this cancellable later. */
                                &err)) {
        if (showMessage){
            QMessageBox::critical(parent ? parent->window() : nullptr, QObject::tr("Error"), err.message());
        }
        return false;
    }

    // reload the containing folder if it is in use but does not have a file monitor
    auto folder = Fm::Folder::findByPath(filePath.parent());
    if(folder && folder->isValid() && folder->isLoaded() && !folder->hasFileMonitor()) {
        folder->reload();
    }

    return true;
}
```

**Comment by damianatorrpm** [comment]
> I took a very simple approach, replaced `g_file_move` with `g_file_set_display_name` and, contrary to what the functions name said, the _real_ file name was changed, not its display name.

I don't know what that with the Fm::FileOperation was (I have other work there).
Of course you are right and regarding the fix for https://github.com/lxqt/libfm-qt/issues/138
only the `changeFileName` function requires chaning.

> That's a little confusing but if `g_file_set_display_name` changes the real file name, it might be good for us. However, your test is needed to see if it solves #138.

Yes! It does change the file name now correctly in google drive.
I believe the reason for this behavior is that `g_file_set_display_name` 
sets the value of what the user visible file name should be and backends like google drive
which use internal hashes as real file name get adjusted accordingly on `g_file_set_display_name`.
Backends where display_name equals the real name i does the right thing and the function
adjusts the real name.

> To test, use this patch but change `changeFileName` as follows:
> 
> ```c++
> bool changeFileName(const Fm::FilePath& filePath, const QString& newName, QWidget* parent, bool showMessage) {
>     Fm::GErrorPtr err;
>     GFilePtr gfile{g_file_set_display_name(filePath.gfile().get(),
>                                             newName.toLocal8Bit().constData(),
>                                             nullptr, /* make this cancellable later. */
>                                             &err)};
>     if(gfile == nullptr) {
>         if (showMessage){
>             QMessageBox::critical(parent ? parent->window() : nullptr, QObject::tr("Error"), err.message());
>         }
>         return false;
>     }
> 
>     // reload the containing folder if it is in use but does not have a file monitor
>     auto folder = Fm::Folder::findByPath(filePath.parent());
>     if(folder && folder->isValid() && folder->isLoaded() && !folder->hasFileMonitor()) {
>         folder->reload();
>     }
> 
>     return true;
> }
> ```
> 
> EDIT: Corrected a mistake in the above code.

I think it may be possible  that the g_file_set_display_name reutrns an error but the gfile exists?
I am curious why there is GFilePtr when there is g_autoptr(GFile) but that does not matter that much.
GFilePtr works well.

This works also but I am no sure if it is possible that the gfile exists but an error occured.
line 1 and line 6 changed
 
> ```c++
> bool changeFileName(const Fm::FilePath& filePath, const QString& newName, QWidget* parent, bool showMessage) {
>     Fm::GErrorPtr err = nullptr;
>     GFilePtr gfile{g_file_set_display_name(filePath.gfile().get(),
>                                             newName.toLocal8Bit().constData(),
>                                             nullptr, /* make this cancellable later. */
>                                             &err)};
>     if(gfile == nullptr || err != nullptr) {
>         if (showMessage){
>             QMessageBox::critical(parent ? parent->window() : nullptr, QObject::tr("Error"), err.message());
>         }
>         return false;
>     }
> 
>     // reload the containing folder if it is in use but does not have a file monitor
>     auto folder = Fm::Folder::findByPath(filePath.parent());
>     if(folder && folder->isValid() && folder->isLoaded() && !folder->hasFileMonitor()) {
>         folder->reload();
>     }
> 
>     return true;
> }
> ```

**Comment by tsujan** [comment]
> only the changeFileName function requires chaning.

The other changes are good too. GLib doc recommends them.

> Yes! It does change the file name now correctly in google drive.

Thanks for testing! I'll make a PR.

> This works also but I am no sure if it is possible that the gfile exists but an error occured.

GLIb doc explicitly says the gfile is NULL if an error occurs. So, there's no need to checking the error.

**Comment by tsujan** [comment]
@agaida Will libfm-qt be released soon? I ask because the new file renaming code might need more tests (I haven't made a PR yet).

**Comment by agaida** [comment]
i think end of february

**Comment by tsujan** [comment]
> i think end of february

Good.

I think https://github.com/lxqt/libfm-qt/pull/511 is not only safe but a big step forward.

**Comment by agaida** [comment]
so i can merge #511 ?

**Comment by tsujan** [comment]
> so i can merge #511 ?

Yes! It's good.

**Pull request closed without merging**
