### PR TITLE
Stop scrolling on view scrollbars during inline renaming

### PR DESCRIPTION
**Pull request by xiota**
This change prevents scrolling during inline renaming when the mouse cursor is over the scrollbars.

### CODE REVIEW

**Comment by tsujan** [comment]
Elsewhere, I asked you to check Dolphin for a reason. While I dedicate time to reviewing your good PRs as fast as possible, I don't think it'll be too much if I expect a little trust from you, in order to avoid explanations like the following.

If the file name is too long, it'll be scrollable inside the renaming editor. The user may want to add something to its start/end. The most natural way is scrolling it with the wheel. Now, if the file is inside a scrollable view, as soon the scrolling reaches a limit inside the editor, it might scroll the view. This annoying behavior is prevented by the code.

Wheel scrolling on the scrollbar can't cause such an interference because the cursor can't be inside the editor at the same time. There's no reason to prevent the user from having it and taking a look up or down before renaming a file.

List and compact views show the same behavior just for the sake of consistency. It isn't needed with them.

**Comment by xiota** [comment]
I opened this as a PR because you appear to treat PRs more favorably than issues.  With an issue, this would have been closed along with a snide remark.  At least this way, I got an explanation.

**Comment by tsujan** [comment]
> you appear to treat PRs more favorably than issues.

No; as you see now ;)

But I really appreciate the works of a good contributor like you. Since your first PRs, I felt that your work was reliable. In one case, your PR was about a duplication but, seeing its elegance, I couldn't help merging it ;)

**Comment by xiota** [comment]
More favorably doesn't mean that you'll accept them.  For instance, you actually wrote an explanation.  With an issue, you would have said (did say) go check out dolphin and closed it.

**Comment by tsujan** [comment]
>  With an issue, you would have said...

I put more time into LXQt than the free time I have. I manage it by avoiding long-winded comments.

**Pull request closed without merging**
