### PR TITLE
Started Qt6 port

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by tsujan** [comment]
Rebasing done for 1.1.0.

**Comment by stefonarch** [comment]
I get
```
 -- Checking for module 'gio-unix-2.0'
--   Found gio-unix-2.0, version 2.74.5
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):                                                                    
  Could NOT find GLIB (missing: GLIB_GIO_UNIX_INCLUDE_DIR) (found suitable     
  version "2.74.5", minimum required is "2.50.0") 
```    

In arch there's no newer version

**Comment by tsujan** [comment]
Strange! There's no problem here:

```
-- Checking for module 'gio-unix-2.0'                                                                                  
--   Found gio-unix-2.0, version 2.74.5                                                                                
-- Found GLIB: /usr/include/glib-2.0;/usr/lib/glib-2.0/include (found suitable version "2.74.5", minimum required is "2.50.0") 
```

Did you install the latest libfm-qt6 from https://github.com/lxqt/libfm-qt/pull/778? Was your build directory clean?

**Comment by stefonarch** [comment]
Related to https://github.com/lxqt/lxqt-build-tools/pull/74 
I get this error also on wip_qt6 in `libqtxdg`.

**Comment by tsujan** [comment]
> Related to lxqt/lxqt-build-tools#74

It's old.

Do you have https://github.com/lxqt/lxqt-build-tools/pull/77?

**Comment by stefonarch** [comment]
That was it, I had it once  but reinstalled `wip-lxqt2-qt6` at some point. Building is running now.

**Comment by tsujan** [comment]
Good.

After compiling and installing it, please check "Always show the tab bar" and verify that:

 1. If you open pcmanfm-qt in your home twice, the second window will have no tab-bar. But if you open the second window in another folder, the tab-bar will be visible.
 2. pcmanfm-qt can't be stopped from LXQt Session Settings.

The first problem seems like a magic to me — maybe I'm tired and don't see something obvious!

**Comment by stefonarch** [comment]
1) no,  both windows have tab bars
2) yes, no way

and 
3) hit ctrl+m, open the hamburger menu and drag the window: menu doesn't close until mouse release.

screen_area_dom_15:30:26_

**Comment by tsujan** [comment]
Any objection to merging? It has been used, tested and completed for more than a year.

**Pull request merged**
