### PR TITLE
Don't select extension on creating new template file

### PR DESCRIPTION
**Pull request by tsujan**
Closes https://github.com/lxqt/pcmanfm-qt/issues/1777

### CODE REVIEW

**Comment by isf63** [comment]
Tested and works great, thanks! Couldn't find any changes other than the selection.

**Comment by stefonarch** [comment]
Looks ok. I just noticed (again) that those libreoffice files generated automatically (don't remember how) have `.desktop` extensions on arch, while on debian with 1.3 they are ok.
screen_area_mar_17:34:31_

screen_area_mar_17:35:29_

**Comment by tsujan** [comment]
>  I just noticed (again) that those libreoffice files generated automatically

They're a mess that LibreOffice creates. To filter them, check `Preferences → Advanced → Templates → Show only user defined templates in menu`

And thanks for testing! I'll merge it after using it for a while.

**Comment by stefonarch** [comment]
I just checked, on debian I've custom files for calc and writer, and no automatically generated ones, but without that option checked. Forgot about the option though, thanks.

**Pull request merged**
