### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/lxqt-desktop/libfm-qt/) for LXQt Desktop/libfm-qt.

### CODE REVIEW

**Comment by tsujan** [comment]
@Bapt17, and dear French translators,

If you think `&#xa0;` shouldn't be used in French, please report that to Qt, instead of changing them in trasnlations `lupdate` will restore it when translations are updated.

**Comment by stefonarch** [comment]
Those are inserted by weblate and not by translaters afaik: at the first new translation after an translation update all those spaces get changed.

**Comment by tsujan** [comment]
> Those are inserted by weblate

You mean, when a translator updates a translation and saves it, Weblate replaces them automatically? If so, the only fix is updating translations before releases, which you always do.

**Comment by stefonarch** [comment]
It would be hard for a human to track down all those spaces I guess. I wrote several times to translators time ago -  they always said that they didn't do it. 

We could update also translations again for git users when french, occitane and some other which I don't remember are done.

**Comment by tsujan** [comment]
> We could update also translations again for git users

It isn't a serious issue. I just thought that translators changed it once in a while. Sorry!

**Pull request merged**
