### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by tsujan** [comment]
This can also be removed now but it's unimportant: https://github.com/lxqt/libfm-qt/blob/46f5717c35bed93b918a987d1a10f454166ca21f/src/core/vfs/vfs-menu.c#L29

**Comment by luis-pereira** [comment]
> This can also be removed now but it's unimportant:
> 
> [libfm-qt/src/core/vfs/vfs-menu.c](https://github.com/lxqt/libfm-qt/blob/46f5717c35bed93b918a987d1a10f454166ca21f/src/core/vfs/vfs-menu.c#L29)
> 
> Line 29 in [46f5717](/lxqt/libfm-qt/commit/46f5717c35bed93b918a987d1a10f454166ca21f)
> 
>  // #include "fm-utils.h"

Done. Force pushed.

**Comment by tsujan** [comment]
If this is finished, please merge it to have a clean ground for your next work. And many thanks for these PRs!

**Comment by tsujan** [comment]
@agaida I have a reason to merge good libfm-qt/pcmanfm-qt PRs that aren't mine. If that's not OK, please tell me!

**Comment by agaida** [comment]
It is ok for me - more verbose: One should not merge own things, unless they are trivial - you have reviewed @luis-pereira\s changes and consider them fine - so it is ok, if you merge them.

**Comment by tsujan** [comment]
> One should not merge own things, unless they are trivial

Yes, I thought so; that's rational. I was just worried about translations and whether I broke them in some way.

**Pull request merged**
