### PR TITLE
WIP: Bump ABI and SOVERSION  to 7.

### PR DESCRIPTION
**Pull request by agaida**
fixes lxqt/libfm-qt/issues/432

### CODE REVIEW

**Comment by tsujan** [comment]
Good.

What if another backward incompatible change is needed to be made to libfm-qt before the next release? I don't have any in my mind though.

**Comment by agaida** [comment]
nothing - tbh - this is esp. important for releases, we could track with age if we really want to.

**Comment by agaida** [comment]
``` diff
@@ -642,11 +642,11 @@ libfm-qt.so.6 libfm-qt6 #MINVER#
  (c++)"Fm::FolderModel::data(QModelIndex const&, int) const@Base" 0.10.0
  (c++)"Fm::FolderModel::dropMimeData(QMimeData const*, Qt::DropAction, int, int, QModelIndex const&)@Base" 0.10.0
  (c++)"Fm::FolderModel::fileInfoFromIndex(QModelIndex const&) const@Base" 0.10.0
+ (c++)"Fm::FolderModel::fileInfoFromPath(Fm::FilePath const&) const@Base" 0.14.2~
  (c++)"Fm::FolderModel::fileSizeChanged(QModelIndex const&)@Base" 0.12.0
  (c++)"Fm::FolderModel::filesAdded(Fm::FileInfoList)@Base" 0.13.0~
  (c++)"Fm::FolderModel::findItemByFileInfo(Fm::FileInfo const*, int*)@Base" 0.12.0
  (c++)"Fm::FolderModel::findItemByName(char const*, int*)@Base" 0.10.0
- (c++)"Fm::FolderModel::findItemByPath(Fm::FilePath const&, int*)@Base" 0.12.0
  (c++)"Fm::FolderModel::flags(QModelIndex const&) const@Base" 0.10.0
  (c++)"Fm::FolderModel::headerData(int, Qt::Orientation, int) const@Base" 0.10.0
  (c++)"Fm::FolderModel::index(int, int, QModelIndex const&) const@Base" 0.10.0
```

**Comment by tsujan** [comment]
Several backward-incompatible changes were made in previous patches. No more seems to be needed before the next release.

**Comment by agaida** [comment]
It's sufficient to bump directly before the release

**Pull request closed without merging**
