### PR TITLE
Optionally show full name

### PR DESCRIPTION
**Pull request by tsujan**
Instead of display name. To be followed by a pcmanfm-qt patch.

### CODE REVIEW

**Comment by tsimonq2** [comment]
Looks good to me.

**Comment by tsujan** [comment]
@agaida Please decide this and its pcmanfm-qt counterpart. I want to implement "shadowed hidden icons"  (PCMan's disabled option) but there are common files -- don't like rebasing ;)

**Comment by PCMan** [comment]
@tsujan I'd suggest renaming the methods to imply what they actually do.
What does "full name" mean?

**Comment by PCMan** [comment]
showRealFileName() or showRawFileName() might be more meaningful I guess.
However, this will cause problems as the real filename might not be in UTF-8 encoding. That's why we have displayName which is always valid unicode. So QString::fromStdString() will fail sometimes. (Although we already assumed UTF-8 in many places, which is not correct either)

**Comment by tsujan** [comment]
@PCMan 

(1) I borrowed that name from *you*. You'd used it in pcmanfm-qt and I found it good enough.

(2) The display name is always used as fallback.

**Comment by tsujan** [comment]
As for the possibility of failure in the case of `QString::fromStdString()`, you're right but, IMO, such exceptions are acceptable because this is optional and not the default.

**Comment by PCMan** [comment]
Oops... The naming is from my code. Sorry for the bad naming. LOL
I should have used a better name. :-(

**Comment by tsujan** [comment]
@PCMan I could change all instances of "fullName" later (to "rawName", for example). I don't think it's a blocker. I think you used "fullName" because of desktop entries and that's quite acceptable.

**Comment by PCMan** [comment]
LGTM

**Comment by tsujan** [comment]
Merging it because it has no conflict with https://github.com/lxqt/libfm-qt/pull/196

**Pull request merged**
