### PR TITLE
intuitive case sensitive checkboxes

### PR DESCRIPTION
**Pull request by coding-moding**
make intuitive case sensitive checkboxes, like in other 1001 search tools and avoid those anti-not-in-insensitive configs)

### CODE REVIEW

**Comment by tsujan** [comment]
This patch fixes nothing. It's only about differences in tastes.

The original author of the code (PCMan) had a style and, IMO, we should respect it when developing his code. I've done so for years, whether I agreed with him or not.

**Comment by coding-moding** [comment]
this patch fixes everything. it's not about style but about 'forget something'

**Comment by tsujan** [comment]
@coding-moding 
"Fixing" has a clear meaning. You don't fix anything by changing "insensitive" to "sensitive" and reversing booleans.

**Comment by coding-moding** [comment]
i fix everything i've described. look at high-grade wide-spread soft (qt creator, msvs, vs code, ff...). they all have "case sensitive" checkbox. coincidence or someone style? don't think so. it's about convenience and intuitiveness.

**Comment by tsujan** [comment]
> it's about convenience and intuitiveness

A developer can freely apply his ideas about "intuitiveness" and "convenience" to his own programs. When it comes to working on others' programs, it's good to have a little respect for the choices of the original authors.

**Comment by PCMan** [comment]
Hi,
Free in free software means freedom.
Please feel free to make it better.
The moment you make someone a committer of your personal project, you
accept the differences between the developer and you. It doesn't matter who
is the original author since we are collaborating as a team and share the
same goals. :)

Given good intention and rationales, please feel free to change whatever
you think I didn't do well. As long as you have good reasoning I'll respect
your decisions and the users' preferences.

Thank you all for working on the project and I hope you all enjoy it.

Regards,
Hong Jen-Jee (PCMan)

tsujan <notifications@github.com> 於 2020年8月2日 週日 上午2:35 寫道：

**Pull request merged**
