### PR TITLE
Removes the FIXME adds info [trashjob.cpp]

### PR DESCRIPTION
**Pull request by damianatorrpm**

### CODE REVIEW

**Comment by agaida** [comment]
@tsujan GTM?

**Comment by tsujan** [comment]
I wouldn't change the original author's comments (PCMan's, in this case) unless necessary. It's *his* code, after all.

**Comment by tsujan** [comment]
I meant GTM.

**Comment by tsujan** [comment]
Oh, sorry, I put the comment in the wrong place!

**Pull request closed without merging**
