### PR TITLE
cleanup trash handling

### PR DESCRIPTION
**Pull request by damianatorrpm**
refactors trash handling, simplifies a lot

### CODE REVIEW

**Comment by tsujan** [comment]
Sorry but no!

The current code is there for NOT opening the trash directory. To monitor the trash, we're only interested in `G_FILE_ATTRIBUTE_TRASH_ITEM_COUNT`, not the whole attributes defined at the top of `fileinfo.cpp` and, definitely, not all the computations done in `folder.cpp`.

I'm afraid a simpler code doesn't mean a better code necessarily.

**Comment by damianatorrpm** [comment]
> Sorry but no!
> 
> The current code is there for NOT opening the trash directory. To monitor the trash, we're only interested in `G_FILE_ATTRIBUTE_TRASH_ITEM_COUNT`, not the whole attributes defined at the top of `fileinfo.cpp` and, definitely, not all the computations done in `folder.cpp`.
> 
> I'm afraid a simpler code doesn't mean a better code necessarily.
I see, the benefits for each approach would be:
1) Not opening:
    not having the trash folder loaded, lower memory consumption
1) opening:
    faster trash loading as it is already preloaded (and folder is a std::shared_ptr<Folder>)

**Comment by tsujan** [comment]
> 2. opening:
> faster trash loading as it is already preloaded (and folder is a std::shared_ptr)

Lots of more computations when the trash isn't opened (= most of the time) and no benefit when it is opened.

**Comment by damianatorrpm** [comment]
Indeed the memory usage is noticeable.

**Pull request closed without merging**
