### PR TITLE
Workaround for DND keyboard modifiers under Wayland

### PR DESCRIPTION
**Pull request by tsujan**
To copy/move/link files directly by DND, `Ctrl` and/or `Shift` modifiers should be pressed only *after* dragging and before dropping because, if they are pressed before dragging, they might mess with the item selection.

However, Wayland doesn't see a keyboard modifier if it's pressed after dragging, rendering DND modifiers impractical. This patch is a simple workaround.

### CODE REVIEW

**Comment by stefonarch** [comment]
Working fine.

**Comment by tsujan** [comment]
So fast! Thanks!

**Comment by tsujan** [comment]
I feel that we might need to release libfm-qt/pcmanfm-qt 1.2.1 before starting an official Qt6 port -- because of Wayland fixes. If so, I'm not sure that the other components that depend on libfm-qt should also have point releases or their current releases should be recompiled by distros.

@yan12125, any suggestion?

**Comment by yan12125** [comment]
> their current releases should be recompiled by distros.

This sounds more natural. To me it's kind of strange to have a new release just for a rebuild. On the other hand, distro packagers are familiar with rebuilding packags against new dependencies. A clear statement for packagers in release notes should be enough.

**Comment by tsujan** [comment]
> A clear statement for packagers in release notes should be enough.

I'll do it. Thanks for the reply!

**Comment by tsujan** [comment]
@yan12125 
If I'm not mistaken, the ABI hasn't changed. The only relevant change is here:

https://github.com/lxqt/libfm-qt/blob/2fd35a5e5495993abfa316cd9ef345c687ecfe88/src/dndactionmenu.h#L36

The argument `QWidget* parent` has been added, which is `nullptr` by default. So, there will be no need to recompilation of `libfm-qt` based apps; only `pcmanfm-qt` will be released because it completes the Wayland changes made to `libfm-qt`.

**Comment by yan12125** [comment]
Generally speaking, changing number or type of C++ function arguments changes the ABI. In this case, the class `DndActionMenu` is not part of public ABI (not declared with `LIBFM_QT_API`), so ABI is not changed.

> So, there will be no need to recompilation of `libfm-qt` based apps

The conclusion is correct :)

**Comment by tsujan** [comment]
Thanks!

**Pull request merged**
