### PR TITLE
Check if the opening app exists before using it

### PR DESCRIPTION
**Pull request by tsujan**
Also, show an error message if there's no app.

### CODE REVIEW

**Comment by agaida** [comment]
Expected:

double click on IDEFIX - get the shares

password dialog should appaer if there are no credentials

apply the credentials

open a folder

open the selected file

**Comment by tsujan** [comment]
I'll check the differences between libfm and libfm-qt in this regard but I can't test smb.

**Comment by tsujan** [comment]
And I love that dog ;)

**Comment by tsujan** [comment]
This PR is correct but not related to the problem it was supposed to solve.

@PCMan, please help! `Windows Network` under `network:///` is seen as `inode/x-shortcut`, which is wrong. Previously, it was seen as `inode/directory` and was mounted. There is a difference between libfm and libfm-qt in this regard, partly in `fileinfo.cpp` and partly in `basicfilelauncher.cpp`.

**Comment by tsujan** [comment]
@PCMan Thanks! If it helps, the first difference I saw was about these lines in `fileinfo.cpp`:
```c++
    tmp = g_file_info_get_content_type(inf.get());
    if(!tmp) {
        tmp = "application/octet-stream";
    }
    mimeType_ = MimeType::fromName(tmp);
```
According to libfm, they could have been:
```c++
    tmp = g_file_info_get_content_type(inf.get());
    if(tmp) {
        mimeType_ = MimeType::fromName(tmp);
    }
```
Then, this may need to be added at the very end, when all mime-types are checked:
```c++
    if(!mimeType_) {
        mimeType_ = MimeType::fromName("application/octet-stream");
    }
```

**Comment by tsujan** [comment]
@agaida The current nullity check and error message are needed but unrelated to the problem you reported; libfm had them too.

**Comment by tsujan** [comment]
> she passed away in spring this year

Sad! A 15-year life span seems good though.

**Comment by agaida** [comment]
@PCMan - i 've no problems with any regression, nothing to be sorry for - indipendence from lbfm far outwight it in short- and long-term tbh. Ok, some users might see this different, with my user hat on me too :P.

**Comment by tsujan** [comment]
@agaida I'm pretty sure that @PCMan will fix it soon. The solution is in his libfm work but I don't know how to transfer it.

Related to this: computer:/// → File System was `inode/directory` before; it's `inode/mount-point` now. With the above-mentioned change in `fileinfo.cpp`, it'll become `inode/directory` again but won't be opened with the current code.

**Comment by agaida** [comment]
sorry, i can't help here - but i'm sure there will be a solution soon - not a big problem right now, only uploaded it to siduction and will apply your patch  - network related things will not work, but at least it don't crash anymore and there will be a nice message popping up. Until solved libfm-qt/pcmanfm-qt will stay in debian/experimental - there is enough work to do fixing the changed symbols, so nearly no harm is done. Ok, Arch and derivative users might see this different.

**Comment by tsujan** [comment]
@agaida  Whenever you have time, please test https://github.com/lxqt/libfm-qt/commit/716e18ae3c5bf23a11e699ec5a5b2ac11fd4b175 ([experiment](https://github.com/lxqt/libfm-qt/tree/experiment) branch).

**Comment by agaida** [comment]
ok - i would call it a step in the right direction:


So, the available machines are displayed correctly.

**Comment by tsujan** [comment]
> But i can't open them

Because there was no mounting ;) What about now: https://github.com/lxqt/libfm-qt/commit/310ba1eef1513227aa452892cf817b39059a2fcd  ?

**Comment by agaida** [comment]
ok, just a second - was on another thing: https://github.com/lxqt/lxqt/issues/1495#issuecomment-395240855

**Comment by agaida** [comment]
ok, just a second - was on another thing: https://github.com/lxqt/lxqt/issues/1495#issuecomment-395240855

ok, there we are

**Comment by tsujan** [comment]
But that's the first dialog above. Are you sure you tried https://github.com/lxqt/libfm-qt/commit/310ba1eef1513227aa452892cf817b39059a2fcd ?

**Comment by agaida** [comment]
no - sorry, my mistake - the current "kind of works"  -  but it is hard to describe

**Comment by tsujan** [comment]
@agaida There's no haste in this. If you're doing another job, I don't want to bother you with this.

**Comment by agaida** [comment]
you don't bother me :) - it's only hard to describe, i dont want to be misleading. Ok, lets start.

1. kill all pcmanfm-qt processes and start it from terminal
2. Single klick on network

3. double click on IDEFIX

after a short meditation local root is opend
4. try open with pcmanfm-qt

voila, something is mounted
5. click ok, the next message appears

6. click on the message - the message disapper, a delete MountOperation is logged


little bit boring, but now to the interesting part - type in the address directly and hit enter

hmm - thats really IDEFIX :)

double click on photos bring up the password dialog
 
log in - we are back to local root :8 - but one difference - the selected folder is now mounted :)

it turns out, that the mounted folder "photos" is really an opened smb-share:

normal operations like open folders or display files is fine


Unmount the mounted share results in a closed pcmanfm-qt - somewhat call the quit routine within the unmount operation.


At all: nice start and a step forward.

**Comment by tsujan** [comment]
So, in short, the result is a better mess :D I tried to do what was done in libfm but some computations should still be different.

**Comment by agaida** [comment]
Yesterday we were one step ahead of the abyss. Today we have taken a decisive step forward. :sunglasses:

**Comment by tsujan** [comment]
> after a short meditation local root is opend

That's the first problem.

> click on the message - the message disapper, a delete MountOperation is logged

Which is the second problem.

**Comment by tsujan** [comment]
@agaida I made a small change by consulting libfm (replaced `FilePath::fromUri` with `FilePath::fromPathStr`); the patch is this now: https://github.com/lxqt/libfm-qt/commit/d2e08c38edcbd116c7cafdeb1c23e2d36a2b8d17

**Comment by PCMan** [comment]
GTM. Failing to open smb:// is another issue. Let's not mixing them. I merge this one first.

**Pull request merged**
