### PR TITLE
add foot to terminals.list

### PR DESCRIPTION
**Pull request by SArpnt**
only tested on artix linux (with the arch linux package) in pcmanfm-qt but i'm guessing this should work just about everywhere since it's a simple change

### CODE REVIEW

**Review by tsujan — APPROVED** [review]

**Comment by Kagukara** [comment]
Can you add footclient as well?

```
[footclient]
noclose_arg=--hold
desktop_id=org.codeberg.dnkl.footclient.desktop
```

**Comment by tsujan** [comment]
> Can you add footclient as well?

If you've tested it and it works, yes, of course.

**Comment by Kagukara** [comment]
> > Can you add footclient as well?
> 
> If you've tested it and it works, yes, of course.

Yes it works, I keep having to manually add it every time there's an update.

**Comment by tsujan** [comment]
> Yes it works,

Thanks, it'll be added soon.

> I keep having to manually add it every time there's an update.

Yes, that's a problem that should be fixed at some point, by supporting a user-defined list (→ https://github.com/lxqt/libfm-qt/issues/922).

**Comment by tsujan** [comment]
@Kagukara
If you use git, please test https://github.com/lxqt/libfm-qt/pull/924, with which, you could create your own `~/.local/share/libfm-qt/terminals.list` with just that entry. Otherwise, `footclient` will be in the next release, regardless of the PR.

**Comment by Kagukara** [comment]
I'm using the AUR package `libfm-qt-git`, so I'm unable to test the terminals_data_dirs branch via git. But thank you for adding `footclient` to the next release, very much appreciated.

**Comment by tsujan** [comment]
> I'm using the AUR package libfm-qt-git

OK. @stefonarch and I have tested the PR and will do more tests. Accompanied by https://github.com/lxqt/pcmanfm-qt/pull/1810, it'll enable the users of v1.4.0 to add terminals without needing to edit `~/.local/share/libfm-qt/terminals.list` manually. You might get it sooner, after the two PRs are merged.

**Comment by Kagukara** [comment]
Just got an update for `libfm-qt-git`, and adding: 
```
[footclient]
noclose_arg=--hold
desktop_id=org.codeberg.dnkl.footclient.desktop
```
to `~/.local/share/libfm-qt/terminals.list` adds `footclient` to the list of Terminal emulators. Thank you.

**Comment by tsujan** [comment]
Thanks for testing!

You could have also entered `footclient` in `PCManFM-Qt → Preferences → Advanced → Terminal emulator` if you also updated PCManFM-Qt. Then, if you wanted to edit that file manually (usually not necessary), you could right click inside the combo-box.

**Comment by Kagukara** [comment]
> You could also have entered `footclient` in `PCManFM-Qt → Preferences → Advanced → Terminal emulator` if you also updated PCManFM-Qt.

I had tried this a while ago and just now, it doesn't work. Only way I got it working was to add it to the `terminals.list`.

**Comment by Kagukara** [comment]
Oh, I had to put `footclient -e %s` in, just like the example for terminal. and it worked.

Added this:
```
[footclient]
open_arg=-e
```
to `~/.local/share/libfm-qt/terminals.list`

**Comment by tsujan** [comment]
> (can't just put footclient)

I added it here and it worked:

```
[footclient]
open_arg=
```

**Comment by Kagukara** [comment]
> > (can't just put footclient)
> 
> I added it here and it worked:
> 
> ```
> [footclient]
> open_arg=
> ```

Ah, just did it as well. Having the file deleted with footclient left in Terminal emulator causes it to not work. I had to switch to a different option then add `footclient`.

**Comment by tsujan** [comment]
> Having the terminals.list file deleted with footclient left in Terminal emulator text box causes it to not work.

I think I know what you mean. That file is read only when the dialog is shown; so, the dialog can't know about manual editing before being cancelled and opened again.

**Comment by stefonarch** [comment]
Tried if `$TERM` or exec `$TERM` would work, it doesn't as it gets sanitized. 
Wondering where I've this env set to xterm - in `lxqt-session-config` it's qterminal.

**Comment by tsujan** [comment]
Neither `libfm-qt` nor `libqtxdg` consult `$TERM`. There was an old discussion as to why `$TERM` was useless (in short, there's no standard way of setting the default terminal in Linux).

Apps that depend on `libqtxdg` (e.g., LXQt Panel) use what's set by `qtxdg-mat` (see `qtxdg-mat def-terminal`). PCManFM-Qt can't use it because it doesn't depend on `libqtxdg`; hence it has its own method — that's what we pay for modularity (which is OK, IMO).

**Comment by tsujan** [comment]
Oh, in addition, `libfm-qt` may need more info on terminals (although that doesn't happen usually). That's another reason.

**Comment by luis-pereira** [comment]
> Neither `libfm-qt` nor `libqtxdg` consults `$TERM`. There was an old discussion as to why `$TERM` was useless (in short, there's no standard way of setting the default terminal in Linux).

The  naming for the `TERM`  variable is very misleading. 
`The environment variable TERM contains a identifier for the text window’s capabilities. You can get a detailed list of these cababilities by using the ‘infocmp’ command, using ‘man 5 terminfo’ as a reference. 
`
Source: https://www.gnu.org/software/gettext/manual/html_node/The-TERM-variable.html

> Apps that depend on `libqtxdg` (e.g., LXQt Panel) use what's set by `qtxdg-mat` (see `qtxdg-mat def-terminal`). PCManFM-Qt can't use it because it doesn't depend on `libqtxdg`; hence it has its own method — that's what we pay for modularity (which is OK, IMO).

Couldn't pcmanfm-qt when running in a LXQt desktop read qtxdg-mat config file ?
No additional dependencies and better user experience.

**Comment by tsujan** [comment]
> Couldn't pcmanfm-qt when running in a LXQt desktop read qtxdg-mat config file ?

Yes, that occurred to me too. But I encountered a problem: Should an app like PCManFM-Qt *write* to that file? IMO, the answer is "no".

That being said, it can solve https://github.com/lxqt/lxqt-archiver/issues/366. It can also be used by any app which needs a terminal emulator.

**Comment by luis-pereira** [comment]
> Yes, that occurred to me too. But I encountered a problem: Should an app like PCManFM-Qt _write_ to that file? IMO, the answer is "no".

There is no need to use the `XdgMimeApps::setDefaultTerminal()` API that would introduce a build time dependency, if that's an issue.
`qtxdg-mat` can be used under LXQt. Runtime dependency only.

**Comment by tsujan** [comment]
No, I meant, "Does an app like PCManFM-Qt have *the right* to change the default terminal of LXQt?" I think it doesn't. Of course, it can programmatically, but that doesn't seem OK to me.

**Comment by tsujan** [comment]
@luis-pereira 
Now that you're here, would you please take a look at https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/48?

**Comment by luis-pereira** [comment]
> No, I meant, "Does an app like PCManFM-Qt have _the right_ to change the default terminal of LXQt?" I think it doesn't. Of course, it can programmatically, but that doesn't seem OK to me.

Under LXQt it can call LXQt default app settings.
p,s. I know that LXQt default app GUI doesn't support Terminal, yet.

**Comment by tsujan** [comment]
> Under LXQt it can call LXQt default app settings.

That seems like a good approach. As you said, we need to add a section to LXQt default app settings. `libfm-qt` will still need its own list, as it contains more info than the terminal command. But its default terminal will be in sync with that of LXQt under LXQt.

All in all, I think it's practical — perhaps the best way.

**Comment by luis-pereira** [comment]
> @luis-pereira Now that you're here, would you please take a look at https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/48?

Done.

**Pull request merged**
