### PR TITLE
Migrate Fm::FileLauncher to the new C++ implementation

### PR DESCRIPTION
**Pull request by PCMan**
Note this still partially depends on two libfm APIs which can be handled later.

### CODE REVIEW

**Comment by agaida** [comment]
ok, there are a few warnings about incompat data types - would it help if i list them?

**Comment by tsujan** [comment]
@agaida I'll look into it tomorrow or the day after it and remove those warnings.

**Comment by agaida** [comment]
i can paste them - as you know i allways compile with all warnings on even if there are pedantic :P

**Comment by tsujan** [comment]
Oh, yes, paste them.

**Comment by tsujan** [comment]
BTW, there some unimportant warnings in previous commits too.

**Comment by tsujan** [comment]
@agaida I removed the warnings I encountered but didn't find any incompatible-data-type one; needing your help.

**Comment by tsujan** [comment]
Before merging this, there are 2 regressions in opening desktop files that I think should be fixed here:

(1) There is no prompt anymore.
(2) Desktop files with `Type=Link` aren't opened.

I'll look into them.

**Comment by agaida** [comment]
@tsujan - i was a little bit irritated yesterday too - background: I run g++8 on my workhorse and g++7 - and see the compat types warning only if i build with g++8 - so it might be that these ones are false positives or better checks that will come with g++8 - will paste them later.

**Comment by tsujan** [comment]
@agaida OK. Tell me if there's a bad warning. Here, there isn't any.

Desktop file issues are fixed. A minor issue still exists with `Type=Link`; I'll try to fix it later

**Comment by tsujan** [comment]
@PCMan Yes, the job should be made async again and that function should be changed. I think it's easy.

**Comment by tsujan** [comment]
@PCMan, I tried to the problem you mentioned. If anything is different from what you have in mind, please change it or tell me to change it.

Again, there's still a small issue to fix before merging.

**Comment by tsujan** [comment]
Another thing to fix: canceling doesn't work in execution prompt dialog.

**Comment by agaida** [comment]
@tsujan - here we go with the current set of PRs:
```
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/filetransferjob.cpp: In member function ‘bool Fm::FileTransferJob::copyDirContent(const Fm::FilePath&, Fm::GFileInfoPtr, Fm::FilePath&, bool)’:
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/filetransferjob.cpp:148:76: warning: unused parameter ‘srcInfo’ [-Wunused-parameter]
 bool FileTransferJob::copyDirContent(const FilePath& srcPath, GFileInfoPtr srcInfo, FilePath& destPath, bool skip) {
                                                               ~~~~~~~~~~~~~^~~~~~~

/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/filechangeattrjob.cpp: In member function ‘bool Fm::FileChangeAttrJob::handleError(Fm::GErrorPtr&, const Fm::FilePath&, const GFileInfoPtr&, Fm::Job::ErrorSeverity)’:
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/filechangeattrjob.cpp:155:69: warning: unused parameter ‘path’ [-Wunused-parameter]
 bool FileChangeAttrJob::handleError(GErrorPtr &err, const FilePath &path, const GFileInfoPtr &info, ErrorSeverity severity) {
                                                     ~~~~~~~~~~~~~~~~^~~~
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/filechangeattrjob.cpp:155:95: warning: unused parameter ‘info’ [-Wunused-parameter]
 bool FileChangeAttrJob::handleError(GErrorPtr &err, const FilePath &path, const GFileInfoPtr &info, ErrorSeverity severity) {
                                                                           ~~~~~~~~~~~~~~~~~~~~^~~~


/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/untrashjob.cpp: In member function ‘virtual void Fm::UntrashJob::exec()’:
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/untrashjob.cpp:34:29: warning: unused variable ‘act’ [-Wunused-variable]
                 ErrorAction act;
                             ^~~

/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/basicfilelauncher.cpp: In member function ‘bool Fm::BasicFileLauncher::launchWithApp(GAppInfo*, const FilePathList&, GAppLaunchContext*)’:
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/basicfilelauncher.cpp:138:33: warning: cast between incompatible function types from ‘void (*)(gpointer)’ {aka ‘void (*)(void*)’} to ‘GFunc’ {aka ‘void (*)(void*, void*)’} [-Wcast-function-type]
     g_list_foreach(uris, (GFunc)g_free, nullptr);
                                 ^~~~~~


/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/archiver.cpp: In member function ‘bool Fm::Archiver::launchProgram(GAppLaunchContext*, const char*, const FilePathList&, const Fm::FilePath&)’:
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/core/archiver.cpp:85:37: warning: cast between incompatible function types from ‘void (*)(gpointer)’ {aka ‘void (*)(void*)’} to ‘GFunc’ {aka ‘void (*)(void*, void*)’} [-Wcast-function-type]
         g_list_foreach(uris, (GFunc)g_free, NULL);
                                     ^~~~~~


/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/filemenu.cpp: In member function ‘void Fm::FileMenu::openFilesWithApp(GAppInfo*)’:
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/filemenu.cpp:311:33: warning: cast between incompatible function types from ‘void (*)(gpointer)’ {aka ‘void (*)(void*)’} to ‘GFunc’ {aka ‘void (*)(void*, void*)’} [-Wcast-function-type]
     g_list_foreach(uris, (GFunc)g_free, nullptr);
                                 ^~~~~~


/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/appmenuview.cpp: In member function ‘void Fm::AppMenuView::addMenuItems(QStandardItem*, MenuCacheDir*)’:
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/appmenuview.cpp:96:45: warning: cast between incompatible function types from ‘gboolean (*)(MenuCacheItem*)’ {aka ‘int (*)(_MenuCacheItem*)’} to ‘GDestroyNotify’ {aka ‘void (*)(void*)’} [-Wcast-function-type]
     g_slist_free_full(list, (GDestroyNotify)menu_cache_item_unref);
                                             ^~~~~~~~~~~~~~~~~~~~~


/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/appchooserdialog.cpp: In member function ‘GAppInfo* Fm::AppChooserDialog::customCommandToApp()’:
/home/agaida/work/code/pkg-main/libfm-qt/snapshot/src/appchooserdialog.cpp:176:41: warning: cast between incompatible function types from ‘void (*)(gpointer)’ {aka ‘void (*)(void*)’} to ‘GFunc’ {aka ‘void (*)(void*, void*)’} [-Wcast-function-type]
             g_list_foreach(apps, (GFunc)g_object_unref, nullptr);
                                         ^~~~~~~~~~~~~~
```

i leave the not so important things in for completeness

**Comment by tsujan** [comment]
@agaida, yes, some of them are from previous PRs. Let's wait until this PR is completed and merged.

**Comment by tsujan** [comment]
Two things that I've seen until now:

(1) The desktop links with native paths without `file://` aren't opened (somehow important).
(2) No error dialog when the path in a desktop link is invalid (not important).

**Comment by tsujan** [comment]
Desktop shortcuts with native paths without `file://` are covered now.

As far as I tested, the only remaining thing is `computer:///`, under which, mount-points can't be opened.

**Comment by PCMan** [comment]
@tsujan I fixed the bugs you found previously. Now mountable paths under computer:/// should be handled correctly.

**Comment by tsujan** [comment]
@PCMan Thank you very much! I'll test the changes soon.

**Comment by tsujan** [comment]
Mount-points are opened correctly now.

**Comment by PCMan** [comment]
So may I merge this?

**Comment by tsujan** [comment]
@PCMan https://github.com/lxqt/pcmanfm-qt/pull/667 depends on it but needs a small change to recognize the quick launch/exec setting.

**Comment by tsujan** [comment]
Or yes, please merge both and I'll fix that minor issue later.

**Comment by agaida** [comment]
GTM

**Comment by tsujan** [comment]
@agaida Wait a few minutes and I'll tell you when ready.

**Comment by agaida** [comment]
ok, so i had to re-test - will take a minute or so

**Comment by tsujan** [comment]
Now it's ready. Please test this and https://github.com/lxqt/pcmanfm-qt/pull/667 again and merge them if they're OK (I tested and they were fine).

**Comment by agaida** [comment]
GTM

**Pull request merged**
