### PR TITLE
Changelog for 0.14.0

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by tsujan** [comment]
Why didn't you push to master directly? I could complete pcmanfm-qt's changelog tomorrow.

**Comment by agaida** [comment]
Thats easy - change it, make as much commits you like to - and i will squash all changelogs into master later. That was the way i wrote my changelogs. It give us the chance to build changelogs within the development process - and we don't have to care how much commits we use and how many edits go into.

**Comment by tsujan** [comment]
Completed.

And sorry for asking the same question (about direct pushing) both in 2018 and in 2019!!

**Comment by agaida** [comment]
no problem, will not make any bad jokes about age ;)

**Pull request merged**
