### PR TITLE
Replace char raw strings literals

### PR DESCRIPTION
**Pull request by luis-pereira**
Avoid memory allocations.
Done by CLAZY_FIXIT="fix-fromCharPtrAllocations".

### CODE REVIEW

**Comment by tsujan** [comment]
It seems good. I'll read it line by line soon. Thanks!

**Comment by luis-pereira** [comment]
I've checked, but another pair of eyes is always a good thing. And you now that source much better than I do.

**Comment by tsujan** [comment]
> I've checked, but another pair of eyes is always a good thing.

Your PRs have always been most accurate. I guess I've become too cautious when it comes to libfm-qt.

**Comment by luis-pereira** [comment]
> Your PRs have always been most accurate. I guess I've become too cautious when it comes to libfm-qt.

That's the power of open source.

**Pull request merged**
