### PR TITLE
Release 0.13.1 changes

### PR DESCRIPTION
**Pull request by agaida**
* including all needed patches.

### CODE REVIEW

**Comment by agaida** [comment]
Same PR for the releases branch - right now i had to figure out how to do these point releases in a sane way. And kind of document it :)

**Comment by agaida** [comment]
@tsujan @PCMan - anything against rebasing master against releases-0.13.1 - if ok for you i would close the related PRs unmerged and forced push the rebased master.

**Comment by tsujan** [comment]
I have nothing against it.

**Comment by tsujan** [comment]
And thanks for 0.13.1.

**Comment by agaida** [comment]
No problem - our first unplanned point release - i'll have to re-write parts of our release scripts for such situations - right now to error prone.

**Comment by agaida** [comment]
Rebased from release branch

**Pull request closed without merging**
