### PR TITLE
Treat scrolling in IconMode and ThumbnailMode the same as CompactMode

### PR DESCRIPTION
**Pull request by xiota**
Potential fix for #722

### CODE REVIEW

**Review by tsujan — CHANGES_REQUESTED** [review]
Here, you've actually removed all the code below those lines.

**Comment by xiota** [comment]
@tsujan  I don't understand your comment.  This PR is based on 1c38ef3.  No code was removed.  Only a couple lines in the comment to refer to the issue number and the condition of the if statement are modified.

**Comment by tsujan** [comment]
> I don't understand your comment.

You changed the condition so that its following block will never be reached, which is equivalent to its removal.

**Comment by xiota** [comment]
Okay.  I don't know how many modes there are.  Is that section of code necessary on your computers?

**Comment by tsujan** [comment]
> Is that section of code necessary on your computers?

The computer is irrelevant.

**Comment by xiota** [comment]
@tsujan
> The computer is irrelevant.

Apparently not, since you stated in #722:

> Please add System Information; it was in the template for a reason.

**Comment by tsujan** [comment]
> Apparently not, since you stated in #722:

It was about system info, as included in the template. We didn't ask about your computer model, how much RAM it has, its graphic card, etc.

**Comment by xiota** [comment]
Okay.  Is it necessary on your computer *setup*?  It looks like smooth scrolling might have been a hack to get around Qt limitations.  Is it even necessary anymore?

**Comment by tsujan** [comment]
If a problem is encountered, first its existence should be proven by providing a way of reproducing it everywhere and, second, it should be fixed. As far as I know, only Gnome devs throw out whole codes when they encounter a problem (like their old codes of desktop icons, systray,...).

**Pull request closed without merging**
